spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.codewithpcodes.oikon.kafka.OrderConfirmation,paymentConfirmation:com.codewithpcodes.ecommerce.notification.PaymentNotificationRequest;
      auto-offset-reset: earliest
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: '*'
#        spring.json.type.mapping: orderConfirmation:com.codewithpcodes.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.codewithpcodes.ecommerce.notification.PaymentNotificationRequest;
#      #      group-id: notificationGroup
#      auto-offset-reset: earliest